version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: weekly
    labels:
      - dependencies

updates:
  - package-ecosystem: npm
    directories:
      - /cli
      - /codeceptjs-e2e
      - /e2e_tests
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: pip
    directory: /qa-integration/pmm_qa
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies
