module.exports = {
  communicationDocs: 'https://www.percona.com/doc/percona-monitoring-and-management/2.x/how-to/configure.html#communication',
  integratedAlertingDocs: 'https://per.co.na/alerting',
  advisorsDocs: 'https://per.co.na/advisors',
  termsOfService: 'https://per.co.na/pmm/platform-terms',
  privacyPolicy: 'https://per.co.na/pmm/platform-privacy',
  forgotPassword: 'https://okta.percona.com/signin/forgot-password',
  imageRendererPlugin: 'https://per.co.na/share_png',
  portalProfile: 'https://portal.percona.com/profile',
  portalDevProfile: 'https://platform-dev.percona.com/profile',
  metricsResolutionDocs: 'https://per.co.na/metrics_resolution',
  dataRetentionDocs: 'https://per.co.na/data_retention',
  telemetryDocs: 'https://per.co.na/telemetry',
  checkForUpdatesDocs: 'https://per.co.na/updates',
  backupManagementDocs: 'https://per.co.na/backup_management',
  microsoftAzureMonitoringDocs: 'https://per.co.na/azure_monitoring',
  sshKeyDocs: 'https://per.co.na/ssh_key',
  prometheusAlertManagerDocs: 'https://per.co.na/alertmanager',
  xtrabackup80Docs: 'https://per.co.na/install_pxb',
};
