import { GrafanaPanel } from '@interfaces/grafanaPanel';

export default class HaproxyInstanceSummary {
  constructor() {}

  url = 'graph/d/haproxy-instance-summary/haproxy-instance-summary';
  metrics: GrafanaPanel[] = [
    { name: 'Connected', type: 'stat' },
    { name: 'Active Servers', type: 'stat' },
    { name: 'Active Sessions', type: 'stat' },
    { name: 'Frontend Sections Status (All)', type: 'stat' },
    { name: 'Backend Sections Status (All)', type: 'stat' },
    { name: 'Active Sessions', type: 'timeSeries' },
    { name: 'Servers in allservers Section', type: 'barTime' },
    { name: 'Sessions', type: 'timeSeries' },
    { name: 'Session Limit', type: 'table' },
    { name: 'Sessions Rate Limit', type: 'table' },
    { name: 'Connections', type: 'timeSeries' },
    { name: 'Frontend Data', type: 'timeSeries' },
    { name: 'Error Requests', type: 'timeSeries' },
    { name: 'Denied Requests', type: 'timeSeries' },
    { name: 'Denied Sessions', type: 'timeSeries' },
    { name: 'Denied Responses', type: 'timeSeries' },
    { name: 'Sessions', type: 'timeSeries' },
    { name: 'Session Limit', type: 'table' },
    { name: 'Maximum Observed Sessions Rate', type: 'table' },
    { name: 'Backend Data', type: 'timeSeries' },
    { name: 'Aborted Data Transfers ', type: 'timeSeries' },
    { name: 'Connection Errors', type: 'timeSeries' },
    { name: 'Connection Establishment Attempts', type: 'timeSeries' },
    { name: 'Connection Reuses', type: 'timeSeries' },
    { name: 'Queue Time', type: 'timeSeries' },
    { name: 'Queued Requests', type: 'timeSeries' },
    { name: 'Denied Requests', type: 'timeSeries' },
    { name: 'Denied Responses', type: 'timeSeries' },
    { name: 'Response Errors', type: 'timeSeries' },
    { name: 'Redispatch Warnings', type: 'timeSeries' },
    { name: 'Failed Header Rewriting Warnings', type: 'timeSeries' },
    { name: 'Active Servers Weight in allservers Section', type: 'table' },
    { name: 'Sessions in allservers Section', type: 'barTime' },
    { name: 'Selections of Servers', type: 'barGauge' },
    { name: 'Sessions', type: 'timeSeries' },
    { name: 'Incoming Data', type: 'timeSeries' },
    { name: 'Outgoing Data', type: 'timeSeries' },
    { name: 'Queued Requests Limits', type: 'empty' },
    { name: 'Queued Requests', type: 'timeSeries' },
    { name: 'Idle Connections', type: 'table' },
    { name: 'Connection Attempts', type: 'timeSeries' },
    { name: 'Connection Reuses', type: 'timeSeries' },
    { name: 'Connection Errors', type: 'timeSeries' },
    { name: 'Request and Response Time', type: 'timeSeries' },
    { name: 'Response Errors', type: 'timeSeries' },
    { name: 'Data Transfers Aborted by the Client', type: 'timeSeries' },
    { name: 'Retry Warnings', type: 'timeSeries' },
    { name: 'Redispatch Warnings', type: 'timeSeries' },
    { name: 'Failed Header Rewriting Warnings', type: 'timeSeries' },
    { name: 'Checks Statistic', type: 'table' },
    { name: 'Data Transfers Aborted by the Server', type: 'timeSeries' },
    { name: 'HTTP Responses by Code', type: 'timeSeries' },
    { name: 'HTTP Requests/Responses', type: 'timeSeries' },
    { name: 'Frontend HTTP Requests', type: 'timeSeries' },
    { name: 'Intercepted HTTP Requests', type: 'timeSeries' },
    { name: 'Uptime', type: 'stat' },
    { name: 'Startup Process', type: 'stat' },
    { name: 'Startup Threads', type: 'stat' },
    { name: 'Per-process Mem Limit', type: 'stat' },
    { name: 'Ulimit-n', type: 'stat' },
    { name: 'Max Open Sockets', type: 'stat' },
    { name: 'Max Concurrent Conn', type: 'stat' },
    { name: 'Max Pipes Number', type: 'stat' },
    { name: 'Pools Memory Usage', type: 'timeSeries' },
    { name: 'Connections', type: 'timeSeries' },
    { name: 'Tasks', type: 'timeSeries' },
    { name: 'Jobs', type: 'timeSeries' },
    { name: 'System Uptime', type: 'stat' },
    { name: 'Load Average', type: 'stat' },
    { name: 'RAM', type: 'stat' },
    { name: 'Memory Available', type: 'stat' },
    { name: 'Virtual Memory', type: 'stat' },
    { name: 'Disk Space', type: 'stat' },
    { name: 'Min Space Available', type: 'stat' },
    { name: 'Node', type: 'text' },
    { name: 'CPU Usage', type: 'timeSeries' },
    { name: 'CPU Saturation and Max Core Usage', type: 'timeSeries' },
    { name: 'Disk I/O and Swap Activity', type: 'stat' },
    { name: 'Network Traffic', type: 'timeSeries' },
  ];
  noDataMetrics: string[] = ['Idle Connections', 'Checks Statistic', 'Disk I/O and Swap Activity'];
  metricsWithData = this.metrics.filter((metric) => !this.noDataMetrics.includes(metric.name));
}
