import { GrafanaPanel } from '../../../intefaces/grafanaPanel';

export default class MysqlInstanceSummaryDashboard {
  constructor() {}

  url = 'graph/d/mysql-instance-summary/mysql-instance-summary';
  metrics: GrafanaPanel[] = [
    { name: 'Node', type: 'unknown' },
    { name: 'MySQL Uptime', type: 'unknown' },
    { name: 'Version', type: 'unknown' },
    { name: 'Current QPS', type: 'unknown' },
    { name: 'InnoDB Buffer Pool Size', type: 'unknown' },
    { name: 'Buffer Pool Size of Total RAM', type: 'unknown' },
    { name: 'Service Summary', type: 'unknown' },
    { name: 'MySQL Connections', type: 'unknown' },
    { name: 'MySQL Aborted Connections', type: 'unknown' },
    { name: 'MySQL Client Thread Activity', type: 'unknown' },
    { name: 'MySQL Thread Cache', type: 'unknown' },
    { name: 'MySQL Temporary Objects', type: 'unknown' },
    { name: 'MySQL Slow Queries', type: 'unknown' },
    { name: 'MySQL Select Types', type: 'unknown' },
    { name: 'MySQL Sorts', type: 'unknown' },
    { name: 'MySQL Table Locks', type: 'unknown' },
    { name: 'MySQL Questions', type: 'unknown' },
    { name: 'MySQL Network Traffic', type: 'unknown' },
    { name: 'MySQL Network Usage Hourly', type: 'unknown' },
    { name: 'MySQL Internal Memory Overview', type: 'unknown' },
    { name: 'Top Command Counters', type: 'unknown' },
    { name: 'Top Command Counters Hourly', type: 'unknown' },
    { name: 'MySQL Handlers', type: 'unknown' },
    { name: 'MySQL Transaction Handlers', type: 'unknown' },
    { name: 'Process States', type: 'unknown' },
    { name: 'Top Process States Hourly', type: 'unknown' },
    { name: 'MySQL Query Cache Memory', type: 'unknown' },
    { name: 'MySQL Query Cache Activity', type: 'unknown' },
    { name: 'MySQL File Openings', type: 'unknown' },
    { name: 'MySQL Open Files', type: 'unknown' },
    { name: 'MySQL Table Open Cache Status', type: 'unknown' },
    { name: 'MySQL Open Tables', type: 'unknown' },
    { name: 'MySQL Table Definition Cache', type: 'unknown' },
    { name: 'System Uptime', type: 'unknown' },
    { name: 'Load Average', type: 'unknown' },
    { name: 'RAM', type: 'unknown' },
    { name: 'Memory Available', type: 'unknown' },
    { name: 'Virtual Memory', type: 'unknown' },
    { name: 'Disk Space', type: 'unknown' },
    { name: 'Min Space Available', type: 'unknown' },
    { name: 'CPU Usage', type: 'unknown' },
    { name: 'CPU Saturation and Max Core Usage', type: 'unknown' },
    { name: 'Disk I/O and Swap Activity', type: 'unknown' },
    { name: 'Network Traffic', type: 'unknown' },
  ];
  noDataMetrics: string[] = [
    'Buffer Pool Size of Total RAM',
    'MySQL Network Usage Hourly',
    'Top Command Counters Hourly',
    'Top Process States Hourly',
    'MySQL Query Cache Memory',
    'MySQL Query Cache Activity',
  ];
}
