export default class MysqlInstanceSummaryDashboard {
  constructor() {}

  url = 'graph/d/mysql-instance-summary/mysql-instance-summary';
  metrics: string[] = [
    'Node',
    'MySQL Uptime',
    'Version',
    'Current QPS',
    'InnoDB Buffer Pool Size',
    'Buffer Pool Size of Total RAM',
    'Service Summary',
    'MySQL Connections',
    'MySQL Aborted Connections',
    'MySQL Client Thread Activity',
    'MySQL Thread Cache',
    'MySQL Temporary Objects',
    'MySQL Slow Queries',
    'MySQL Select Types',
    'MySQL Sorts',
    'MySQL Table Locks',
    'MySQL Questions',
    'MySQL Network Traffic',
    'MySQL Network Usage Hourly',
    'MySQL Internal Memory Overview',
    'Top Command Counters',
    'Top Command Counters Hourly',
    'MySQL Handlers',
    'MySQL Transaction Handlers',
    'Process States',
    'Top Process States Hourly',
    'MySQL Query Cache Memory',
    'MySQL Query Cache Activity',
    'MySQL File Openings',
    'MySQL Open Files',
    'MySQL Table Open Cache Status',
    'MySQL Open Tables',
    'MySQL Table Definition Cache',
    'System Uptime',
    'Load Average',
    'RAM',
    'Memory Available',
    'Virtual Memory',
    'Disk Space',
    'Min Space Available',
    'CPU Usage',
    'CPU Saturation and Max Core Usage',
    'Disk I/O and Swap Activity',
    'Network Traffic',
  ];
  noDataMetrics: string[] = [
    'Buffer Pool Size of Total RAM',
    'MySQL Network Usage Hourly',
    'Top Command Counters Hourly',
    'Top Process States Hourly',
    'MySQL Query Cache Memory',
    'MySQL Query Cache Activity',
  ];
}
