import { GrafanaPanel } from '../../../intefaces/grafanaPanel';

export default class MysqlInstanceOverview {
  constructor() {}

  url = 'graph/d/mysql-instance-overview/mysql-instances-overview';
  metrics: GrafanaPanel[] = [
    { name: 'Services', type: 'stat' },
    { name: 'Min MySQL Uptime', type: 'stat' },
    { name: 'Max MySQL Uptime', type: 'stat' },
    { name: 'Total Current QPS', type: 'stat' },
    { name: 'Total InnoDB Buffer Pool Size', type: 'stat' },
    { name: 'Top MySQL Used Connections', type: 'stat' },
    { name: 'Top MySQL Client Threads Connected', type: 'stat' },
    { name: 'Top MySQL Idle Client Threads', type: 'stat' },
    { name: 'Top MySQL Threads Cached', type: 'stat' },
    { name: 'Top 5 MySQL Used Connections', type: 'timeSeries' },
    { name: 'MySQL Used Connections', type: 'polyStat' },
    { name: 'Top 5 MySQL Aborted Connections', type: 'timeSeries' },
    { name: 'Aborted Connections', type: 'polyStat' },
    { name: 'Top 5 MySQL Client Threads Connected', type: 'timeSeries' },
    { name: 'MySQL Client Threads Connected', type: 'polyStat' },
    { name: 'Top 5 MySQL Active Client Threads', type: 'timeSeries' },
    { name: 'MySQL Idle Client Threads', type: 'polyStat' },
    { name: 'Top 5 MySQL Thread Cached', type: 'timeSeries' },
    { name: 'Percentage of Cached MySQL Threads', type: 'polyStat' },
    { name: 'Top MySQL Queries', type: 'stat' },
    { name: 'Top MySQL Questions', type: 'stat' },
    { name: 'Top InnoDB I/O Data Reads', type: 'stat' },
    { name: 'Top InnoDB I/O Data Writes', type: 'stat' },
    { name: 'Top Data Fsyncs', type: 'stat' },
    { name: 'Top 5 MySQL Queries', type: 'timeSeries' },
    { name: 'MySQL QPS', type: 'polyStat' },
    { name: 'Top 5 MySQL Questions', type: 'timeSeries' },
    { name: 'MySQL Questions in Queries', type: 'polyStat' },
    { name: 'Top 5 Data Reads', type: 'timeSeries' },
    { name: 'Percentage of Data Read', type: 'polyStat' },
    { name: 'Top 5 Data Writes', type: 'timeSeries' },
    { name: 'Percentage of Data Writes', type: 'polyStat' },
    { name: 'Top 5 Data Fsyncs', type: 'timeSeries' },
    { name: 'Percentage of Data Fsyncs', type: 'polyStat' },
    { name: 'Top MySQL Questions', type: 'stat' },
    { name: 'Top MySQL Selects', type: 'stat' },
    { name: 'Top MySQL Sorts', type: 'stat' },
    { name: 'Top MySQL Aborted Connections', type: 'stat' },
    { name: 'Top MySQL Table Locks', type: 'stat' },
    { name: 'MySQL Temporary Objects', type: 'timeSeries' },
    { name: 'MySQL Temporary Objects', type: 'polyStat' },
    { name: 'Top 5 MySQL Selects', type: 'timeSeries' },
    { name: 'MySQL Selects', type: 'polyStat' },
    { name: 'Top 5 MySQL Sorts', type: 'timeSeries' },
    { name: 'MySQL Sorts', type: 'polyStat' },
    { name: 'Top 5 MySQL Table Locks', type: 'timeSeries' },
    { name: 'MySQL Table Locks', type: 'polyStat' },
    { name: 'Top MySQL Incoming Network Traffic', type: 'stat' },
    { name: 'Top MySQL Outgoing Network Traffic', type: 'stat' },
    { name: 'Top MySQL Used Query Cache', type: 'stat' },
    { name: 'Top Percentage of File Openings to Opened Files', type: 'stat' },
    { name: 'Top Percentage of Opened Files to the Limit', type: 'stat' },
    { name: 'Top 5 MySQL Incoming Network Traffic', type: 'timeSeries' },
    { name: 'Top 5 MySQL Outgoing Network Traffic', type: 'timeSeries' },
    { name: 'MySQL Query Cache Size', type: 'unknown' },
    { name: 'MySQL Used Query Cache', type: 'unknown' },
    { name: 'Top 5 MySQL File Openings', type: 'timeSeries' },
    { name: 'Percentage of File Openings to Opened Files', type: 'polyStat' },
    { name: 'Top 5 MySQL Opened Files', type: 'timeSeries' },
    { name: 'Percentage of Opened Files to the Limit', type: 'polyStat' },
    { name: 'Top Open Cache Miss Ratio', type: 'stat' },
    { name: 'Min MySQL Opened Table Definitions', type: 'stat' },
    { name: 'Top MySQL Opened Table Definitions', type: 'stat' },
    { name: 'Top MySQL Open Table Definitions', type: 'stat' },
    { name: 'Top Open Table Definitions to Definition Cache', type: 'stat' },
    { name: 'Lowest 5 Open Cache Hit Ratio', type: 'timeSeries' },
    { name: 'Open Cache Miss Ratio', type: 'polyStat' },
    { name: 'MySQL Table Definition Cache', type: 'stat' },
    { name: 'Top 5 MySQL Opened Table Definitions', type: 'timeSeries' },
    { name: 'Top 5 MySQL Open Table Definitions', type: 'timeSeries' },
    { name: 'Percentage of Open Table Definitions to Table Definition Cache', type: 'polyStat' },
  ];
  noDataMetrics: string[] = [
    'MySQL Query Cache Size',
    'MySQL Used Query Cache',
    'Top MySQL Used Query Cache',
  ];
}
