- name: Set Facts.
  set_fact:
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"
    cacheable: true

- debug:
    msg: "Value of PERCONA_TELEMETRY_URL is : {{ PERCONA_TELEMETRY_URL }}"

- name: Clean dnf
  become: true
  command: dnf clean all -y
  when: ansible_os_family == "RedHat"

- name: Disable dnf postgresql for RHEL8
  become: true
  command: dnf module disable postgresql -y
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

- name: install Percona Platform for PostgreSQL deb packages
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: latest
  vars:
    packages:
    - percona-postgresql
    - percona-postgresql-14
    - percona-postgresql-all
    - percona-postgresql-client
    - percona-postgresql-client-14
    - percona-postgresql-common
    - percona-postgresql-contrib
    - percona-postgresql-doc
    - percona-postgresql-doc-14
    - percona-postgresql-plperl-14
    - percona-postgresql-plpython3-14
    - percona-postgresql-pltcl-14
    - percona-postgresql-server-dev-14
    - percona-postgresql-server-dev-all
    - percona-postgresql-14-dbgsym
    - percona-postgresql-client-14-dbgsym
    - percona-postgresql-plperl-14-dbgsym
    - percona-postgresql-plpython3-14-dbgsym
    - percona-postgresql-pltcl-14-dbgsym
    - postgresql-client-common
    - postgresql-common
  when: ansible_os_family == "Debian"
  environment:
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: install Percona Platform for PostgreSQL rpm packages for RHEL
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - percona-postgresql-client-common
      - percona-postgresql-common
      - percona-postgresql14
      - percona-postgresql14-contrib
      - percona-postgresql14-debuginfo
      - percona-postgresql14-devel
      - percona-postgresql14-docs
      - percona-postgresql14-libs
      - percona-postgresql14-llvmjit
      - percona-postgresql14-plpython3
      - percona-postgresql14-plperl
      - percona-postgresql14-pltcl
      - percona-postgresql14-server
      - percona-postgresql14-test
      - percona-postgresql14-contrib-debuginfo
      - percona-postgresql14-debuginfo
      - percona-postgresql14-debugsource
      - percona-postgresql14-devel-debuginfo
      - percona-postgresql14-libs-debuginfo
      - percona-postgresql14-plperl-debuginfo
      - percona-postgresql14-pltcl-debuginfo
      - percona-postgresql14-plpython3-debuginfo
      - percona-postgresql14-server-debuginfo
  when: ansible_os_family == "RedHat"
  environment:
    PERCONA_TELEMETRY_URL: "https://check-dev.percona.com/v1/telemetry/GenericReport"

- name: Determine required PostgreSQL dev package for RHEL
  set_fact:
    pg_dev_package: >-
      {{ 'percona-postgresql-server-dev-all'
        if (pg_version_to_install | string is version('14.17', '<=', strict=True))
        else 'percona-postgresql-common-dev' }}
  when: ansible_os_family == "RedHat"

- name: Install PostgreSQL dev package on RHEL
  yum:
    name: "{{ pg_dev_package }}"
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"
