import DashboardInterface from '@interfaces/dashboard';
import { GrafanaPanel } from '@interfaces/grafanaPanel';

export default class NodesOverviewDashboard implements DashboardInterface {
  url = 'graph/d/node-instance-overview/nodes-overview';
  acceptableNoDataCount = 3;
  metrics: GrafanaPanel[] = [
    { name: 'Nodes', type: 'unknown' },
    { name: 'Min Node Uptime', type: 'unknown' },
    { name: 'DB Instances', type: 'unknown' },
    { name: 'Min DB Uptime', type: 'unknown' },
    { name: 'Total Virtual CPUs', type: 'unknown' },
    { name: 'Total RAM', type: 'unknown' },
    { name: 'Virtual Memory Total', type: 'unknown' },
    { name: 'Disk Space Total', type: 'unknown' },
    { name: 'Regions', type: 'unknown' },
    { name: 'Types', type: 'unknown' },
    { name: 'Nodes', type: 'unknown' },
    { name: 'Regions', type: 'unknown' },
    { name: 'Service Types', type: 'unknown' },
    { name: 'Services', type: 'unknown' },
    { name: 'Top Usage', type: 'unknown' },
    { name: 'Top Steal', type: 'unknown' },
    { name: 'Top I/O Wait', type: 'unknown' },
    { name: 'Top Saturation', type: 'unknown' },
    { name: 'Top Switches', type: 'unknown' },
    { name: 'Top Load', type: 'unknown' },
    { name: 'Top Runnable Procs', type: 'unknown' },
    { name: 'Top Blocked Procs', type: 'unknown' },
    { name: 'Top 5 CPU Usage', type: 'unknown' },
    { name: 'CPU Usage', type: 'unknown' },
    { name: 'Top 5 CPU Steal', type: 'unknown' },
    { name: 'CPU Steal', type: 'unknown' },
    { name: 'Top 5 CPU I/O Wait', type: 'unknown' },
    { name: 'CPU I/O Wait', type: 'unknown' },
    { name: 'Top 5 CPU Saturation', type: 'unknown' },
    { name: 'CPU Saturation', type: 'unknown' },
    { name: 'Top 5 Context Switches', type: 'unknown' },
    { name: 'Switches', type: 'unknown' },
    { name: 'Top 5 Runnable Processes', type: 'unknown' },
    { name: 'Runnable Processes', type: 'unknown' },
    { name: 'Top 5 Blocked Processes', type: 'unknown' },
    { name: 'Blocked Processes', type: 'unknown' },
    { name: 'Min Memory Available', type: 'unknown' },
    { name: 'Min Virtual Memory Available', type: 'unknown' },
    { name: 'Top File Cache Active Memory', type: 'unknown' },
    { name: 'Min Swap Available', type: 'unknown' },
    { name: 'Top Swap Reads', type: 'unknown' },
    { name: 'Top Swap Writes', type: 'unknown' },
    { name: 'Free Memory Percent', type: 'unknown' },
    { name: 'Available Virtual Memory Percent', type: 'unknown' },
    { name: 'Free Swap Space Percent', type: 'unknown' },
    { name: 'Top 5 Used Memory', type: 'unknown' },
    { name: 'Top 5 Free Memory', type: 'unknown' },
    { name: 'Top 5 Used Virtual Memory', type: 'unknown' },
    { name: 'Top 5 Available Virtual Memory', type: 'unknown' },
    { name: 'Top 5 Used Swap Space', type: 'unknown' },
    { name: 'Top 5 Free Swap Space', type: 'unknown' },
    { name: 'Top 5 Swap In (Reads)', type: 'unknown' },
    { name: 'Top 5 Swap Out (Writes)', type: 'unknown' },
    { name: 'Min Free Space Available', type: 'unknown' },
    { name: 'Top I/O Load', type: 'unknown' },
    { name: ' Top Disk Latency', type: 'unknown' },
    { name: ' Top Disk Operations', type: 'unknown' },
    { name: ' Top Disk Bandwidth', type: 'unknown' },
    { name: ' Top I/O Activity', type: 'unknown' },
    { name: 'Top 5 Disk I/O Load', type: 'unknown' },
    { name: 'Disk I/O Load', type: 'unknown' },
    { name: 'Top 5 Disk Latency', type: 'unknown' },
    { name: ' Disk Latency', type: 'unknown' },
    { name: 'Top 5 Disk Bandwidth', type: 'unknown' },
    { name: ' Disk Bandwidth', type: 'unknown' },
    { name: 'Top 5 I/O Activity', type: 'unknown' },
    { name: 'I/O Activity', type: 'unknown' },
    { name: ' Top Receive Network Traffic', type: 'unknown' },
    { name: ' Top Transmit Network Traffic', type: 'unknown' },
    { name: 'Top Errors', type: 'unknown' },
    { name: 'Top Drop', type: 'unknown' },
    { name: 'Top Retransmission', type: 'unknown' },
    { name: 'Top Retransmit rate', type: 'unknown' },
    { name: 'Top 5 Network Traffic', type: 'unknown' },
    { name: 'Network Traffic', type: 'unknown' },
    { name: 'Top 5 Local Network Errors', type: 'unknown' },
    { name: 'Errors', type: 'unknown' },
    { name: 'Top 5 TCP Retransmission', type: 'unknown' },
    { name: 'Retransmission', type: 'unknown' },
    { name: 'Top 5 Local Network Drop', type: 'unknown' },
    { name: 'Drop', type: 'unknown' },
  ];
  noDataMetrics: string[] = [];
}
