import { GrafanaPanel } from '@interfaces/grafanaPanel';

export default class ValkeyCommandDetailDashboard {
  url = 'graph/d/valkey-command-details/valkey-redis-command-detail';
  metrics: GrafanaPanel[] = [
    { name: 'All - Total Commands/Sec', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - Read and Write Rate', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - Read and Write Rate', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - Read and Write Rate', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - Read and Write Rate', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - Read and Write Rate', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - Read and Write Rate', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - Command by Type', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - Command by Type', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - Command by Type', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - Command by Type', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - Command by Type', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - Command by Type', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - Top 10 Commands by Total TIme', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - Top 10 Commands by Total TIme', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - Top 10 Commands by Total TIme', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - Top 10 Commands by Total TIme', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - Top 10 Commands by Total TIme', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - Top 10 Commands by Total TIme', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - Total Time Spent by Command/Sec', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - Total Time Spent by Command/Sec', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - Total Time Spent by Command/Sec', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - Total Time Spent by Command/Sec', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - Total Time Spent by Command/Sec', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - Total Time Spent by Command/Sec', type: 'unknown' },
    // For some reason these panels have identical names even though they are different
    { name: 'Commands Totals', type: 'unknown' },
    { name: 'Commands Totals', type: 'unknown' },
    { name: 'Commands Totals', type: 'unknown' },
    { name: 'Commands Totals', type: 'unknown' },
    { name: 'Commands Totals', type: 'unknown' },
    { name: 'Commands Totals', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - Command Percentiles', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - Command Percentiles', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - Command Percentiles', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - Command Percentiles', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - Command Percentiles', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - Command Percentiles', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - GET Latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - GET Latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - GET Latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - GET Latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - GET Latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - GET Latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - RPOP Latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - RPOP Latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - RPOP Latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - RPOP Latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - RPOP Latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - RPOP Latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - SET Latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - SET Latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - SET Latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - SET Latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - SET Latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - SET Latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - HSET Latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - HSET Latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - HSET Latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - HSET Latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - HSET Latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - HSET Latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - LPOP Latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - LPOP Latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - LPOP Latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - LPOP Latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - LPOP Latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - LPOP Latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - LRANGE Latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - LRANGE Latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - LRANGE Latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - LRANGE Latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - LRANGE Latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - LRANGE Latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - PSYNC Latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - PSYNC Latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - PSYNC Latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - PSYNC Latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - PSYNC Latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - PSYNC Latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - RPUSH latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - RPUSH latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - RPUSH latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - RPUSH latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - RPUSH latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - RPUSH latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - LPUSH Latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - LPUSH Latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - LPUSH Latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - LPUSH Latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - LPUSH Latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - LPUSH Latency', type: 'unknown' },
  ];
}
