import { GrafanaPanel } from '@interfaces/grafanaPanel';

export default class ValkeyCommandDetailDashboard {
  url = 'graph/d/valkey-command-details/valkey-redis-command-detail';
  metrics: GrafanaPanel[] = [
    { name: 'All - Total Commands / sec', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - Read and Write rate', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - Read and Write rate', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - Read and Write rate', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - Read and Write rate', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - Read and Write rate', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - Read and Write rate', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - command ops/sec', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - command ops/sec', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - command ops/sec', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - command ops/sec', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - command ops/sec', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - command ops/sec', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - top 10 total time by command', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - top 10 total time by command', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - top 10 total time by command', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - top 10 total time by command', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - top 10 total time by command', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - top 10 total time by command', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - total Time Spent by Command / sec', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - total Time Spent by Command / sec', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - total Time Spent by Command / sec', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - total Time Spent by Command / sec', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - total Time Spent by Command / sec', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - total Time Spent by Command / sec', type: 'unknown' },
    { name: 'Commands Totals', type: 'unknown' },
    { name: 'Commands Totals', type: 'unknown' },
    { name: 'Commands Totals', type: 'unknown' },
    { name: 'Commands Totals', type: 'unknown' },
    { name: 'Commands Totals', type: 'unknown' },
    { name: 'Commands Totals', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - command percentiles', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - command percentiles', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - command percentiles', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - command percentiles', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - command percentiles', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - command percentiles', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - get latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - get latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - get latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - get latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - get latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - get latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - rpop latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - rpop latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - rpop latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - rpop latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - rpop latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - rpop latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - set latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - set latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - set latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - set latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - set latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - set latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - hset latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - hset latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - hset latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - hset latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - hset latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - hset latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - lpop latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - lpop latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - lpop latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - lpop latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - lpop latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - lpop latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - lrange latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - lrange latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - lrange latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - lrange latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - lrange latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - lrange latency', type: 'unknown' },
    { name: 'valkey-primary-1-svc-* - psync latency', type: 'unknown' },
    { name: 'valkey-primary-2-svc-* - psync latency', type: 'unknown' },
    { name: 'valkey-primary-3-svc-* - psync latency', type: 'unknown' },
    { name: 'valkey-replica-4-svc-* - psync latency', type: 'unknown' },
    { name: 'valkey-replica-5-svc-* - psync latency', type: 'unknown' },
    { name: 'valkey-replica-6-svc-* - psync latency', type: 'unknown' },
    { name: 'rpush latency', type: 'unknown' },
    { name: 'lpush latency', type: 'unknown' },
  ];
}
