class PostgresqlInstancesOverviewExtendedDashboard {
  constructor() {
    this.url = 'graph/d/postgresql-overview-extended/postgresql-instances-overview-extended';
    this.metrics = [
      'Services',
      'Max Active Connections',
      'Total Disk-Page Buffers',
      'Total Memory Size for each Sort',
      'Total Shared Buffers',
      'Services Autovacuum',
      'Top 5 PostgreSQL Connections',
      'Idle Connections',
      'Top 5 Active Connections',
      'Active Connections',
      'Autovacuum',
      'Autovacuum',
      'Total Tuples',
      'Max Fetched Tuples',
      'Max Returned Tuples',
      'Max Inserted Tuples',
      'Max Updated Tuples',
      'Max Deleted Tuples',
      'Top 5 Fetched Tuples Rate',
      'Fetched Tuples Rate',
      'Top 5 Returned Tuples Rate',
      'Returned Tuples Rate',
      'Top 5 Inserted Tuples Rate',
      'Inserted Tuples Rate',
      'Top 5 Updated Tuples Rate',
      'Updated Tuples Rate',
      'Top 5 Deleted Tuples Rate',
      'Deleted Tuples Rate',
      'Total Transactions',
      'Max Commits Transactions',
      'Max Rollback Transactions',
      'Max Transaction Duration',
      'Max Number of Temp Files',
      'Max Size of Temp Files',
      'Top 5 Commit Transactions',
      'Commit Transactions',
      'Top 5 Rollbacks Transactions',
      'Rollback Transactions',
      'Top 5 Duration of Active Transactions',
      'Duration of Active Transactions',
      'Top 5 Duration of Other Transactions',
      'Duration of Other Transactions',
      'Top 5 Number of Temp Files',
      'Number of Temp Files',
      'Top 5 Size of Temp Files',
      'Size of Temp Files',
      'Total Locks',
      'Total Deadlocks',
      'Total Conflicts',
      'Min Cache Hit Ratio',
      'Max Cache Hit Ratio',
      'Total Canceled Queries',
      'Top 5 Locks',
      'Locks',
      'Top 5 Deadlocks',
      'Deadlocks',
      'Top 5 Conflicts',
      'Conflicts',
      'Top 5 Lowest Cache Hit Ratio',
      'Cache Hit Ratio',
      'Top 5 Canceled Queries',
      'Canceled Queries',
      'Total Blocks Operations',
      'Max Blocks Writes',
      'Max Blocks Reads',
      'Max Allocated Buffers',
      'Total Written Files to disk',
      'Total Files Synchronization to Disk',
      'Top 5 Read Operations with Blocks',
      'Read Operations with Blocks',
      'Top 5 Write Operations with Blocks',
      'Write Operations with Blocks',
      'Top 5 Allocated Buffers',
      'Allocated Buffers',
      'Top 5 Fsync calls by a backend',
      'Fsync calls by a backend',
      'Top 5 Written directly by a backend',
      'Written directly by a backend',
      'Top 5 Written by the background writer',
      'Written by the background writer',
      'Top 5 Written during checkpoints',
      'Written during checkpoints',
      'Top 5 Files Synchronization to disk',
      'Files Synchronization to disk',
      'Top 5 Written Files to Disk',
      'Written Files to Disk',
    ];
  }
}

module.exports = new PostgresqlInstancesOverviewExtendedDashboard();
module.exports.PostgresqlTopQueriesDashboard = PostgresqlInstancesOverviewExtendedDashboard;
