- name: Debug variable backup
  debug:
    var: backup

- name: Install percona xtrabackup 8.4
  shell: |
    docker exec --user root {{ container_name }} percona-release enable-only tools release
    docker exec --user root {{ container_name }} apt-get update
    docker exec --user root {{ container_name }} apt-get install -y percona-xtrabackup-84
  when: ps_version | replace('_', '') | int == 84
  loop: "{{ range(1, nodes_count | int + 1) | list }}"

- name: Install percona xtrabackup 8.0
  shell: |
    docker exec --user root {{ container_name }} percona-release enable-only tools release
    docker exec --user root {{ container_name }} apt-get update
    docker exec --user root {{ container_name }} apt-get install -y percona-xtrabackup-84
  when: ps_version | replace('_', '') | int == 80
  loop: "{{ range(1, nodes_count | int + 1) | list }}"

- name: Install minio for S3 compatible buckets
  include_tasks: ../tasks/create_minio_container.yml