class ValkeyCommandDetailDashboard {
  constructor() {
    this.url = 'graph/d/valkey-command-details/valkey-redis-command-detail';
    this.metrics = [
      'All - Total Commands/Sec',
      'valkey-primary-1-svc-* - Read and Write Rate',
      'valkey-primary-2-svc-* - Read and Write Rate',
      'valkey-primary-3-svc-* - Read and Write Rate',
      'valkey-replica-4-svc-* - Read and Write Rate',
      'valkey-replica-5-svc-* - Read and Write Rate',
      'valkey-replica-6-svc-* - Read and Write Rate',
      'valkey-primary-1-svc-* - Command by Type',
      'valkey-primary-2-svc-* - Command by Type',
      'valkey-primary-3-svc-* - Command by Type',
      'valkey-replica-4-svc-* - Command by Type',
      'valkey-replica-5-svc-* - Command by Type',
      'valkey-replica-6-svc-* - Command by Type',
      'valkey-primary-1-svc-* - Top 10 Commands by Total TIme',
      'valkey-primary-2-svc-* - Top 10 Commands by Total TIme',
      'valkey-primary-3-svc-* - Top 10 Commands by Total TIme',
      'valkey-replica-4-svc-* - Top 10 Commands by Total TIme',
      'valkey-replica-5-svc-* - Top 10 Commands by Total TIme',
      'valkey-replica-6-svc-* - Top 10 Commands by Total TIme',
      'valkey-primary-1-svc-* - Total Time Spent by Command/Sec',
      'valkey-primary-2-svc-* - Total Time Spent by Command/Sec',
      'valkey-primary-3-svc-* - Total Time Spent by Command/Sec',
      'valkey-replica-4-svc-* - Total Time Spent by Command/Sec',
      'valkey-replica-5-svc-* - Total Time Spent by Command/Sec',
      'valkey-replica-6-svc-* - Total Time Spent by Command/Sec',
      'Commands Totals',
      'Commands Totals',
      'Commands Totals',
      'Commands Totals',
      'Commands Totals',
      'Commands Totals',
      'valkey-primary-1-svc-* - Command Percentiles',
      'valkey-primary-2-svc-* - Command Percentiles',
      'valkey-primary-3-svc-* - Command Percentiles',
      'valkey-replica-4-svc-* - Command Percentiles',
      'valkey-replica-5-svc-* - Command Percentiles',
      'valkey-replica-6-svc-* - Command Percentiles',
      'valkey-primary-1-svc-* - GET Latency',
      'valkey-primary-2-svc-* - GET Latency',
      'valkey-primary-3-svc-* - GET Latency',
      'valkey-replica-4-svc-* - GET Latency',
      'valkey-replica-5-svc-* - GET Latency',
      'valkey-replica-6-svc-* - GET Latency',
      'valkey-primary-1-svc-* - RPOP Latency',
      'valkey-primary-2-svc-* - RPOP Latency',
      'valkey-primary-3-svc-* - RPOP Latency',
      'valkey-replica-4-svc-* - RPOP Latency',
      'valkey-replica-5-svc-* - RPOP Latency',
      'valkey-replica-6-svc-* - RPOP Latency',
      'valkey-primary-1-svc-* - SET Latency',
      'valkey-primary-2-svc-* - SET Latency',
      'valkey-primary-3-svc-* - SET Latency',
      'valkey-replica-4-svc-* - SET Latency',
      'valkey-replica-5-svc-* - SET Latency',
      'valkey-replica-6-svc-* - SET Latency',
      'valkey-primary-1-svc-* - HSET Latency',
      'valkey-primary-2-svc-* - HSET Latency',
      'valkey-primary-3-svc-* - HSET Latency',
      'valkey-replica-4-svc-* - HSET Latency',
      'valkey-replica-5-svc-* - HSET Latency',
      'valkey-replica-6-svc-* - HSET Latency',
      'valkey-primary-1-svc-* - LPOP Latency',
      'valkey-primary-2-svc-* - LPOP Latency',
      'valkey-primary-3-svc-* - LPOP Latency',
      'valkey-replica-4-svc-* - LPOP Latency',
      'valkey-replica-5-svc-* - LPOP Latency',
      'valkey-replica-6-svc-* - LPOP Latency',
      'valkey-primary-1-svc-* - LRANGE Latency',
      'valkey-primary-2-svc-* - LRANGE Latency',
      'valkey-primary-3-svc-* - LRANGE Latency',
      'valkey-replica-4-svc-* - LRANGE Latency',
      'valkey-replica-5-svc-* - LRANGE Latency',
      'valkey-replica-6-svc-* - LRANGE Latency',
      'valkey-primary-1-svc-* - PSYNC Latency',
      'valkey-primary-2-svc-* - PSYNC Latency',
      'valkey-primary-3-svc-* - PSYNC Latency',
      'valkey-replica-4-svc-* - PSYNC Latency',
      'valkey-replica-5-svc-* - PSYNC Latency',
      'valkey-replica-6-svc-* - PSYNC Latency',
      'valkey-primary-1-svc-* - RPUSH latency',
      'valkey-primary-2-svc-* - RPUSH latency',
      'valkey-primary-3-svc-* - RPUSH latency',
      'valkey-replica-4-svc-* - RPUSH latency',
      'valkey-replica-5-svc-* - RPUSH latency',
      'valkey-replica-6-svc-* - RPUSH latency',
      'valkey-primary-1-svc-* - LPUSH Latency',
      'valkey-primary-2-svc-* - LPUSH Latency',
      'valkey-primary-3-svc-* - LPUSH Latency',
      'valkey-replica-4-svc-* - LPUSH Latency',
      'valkey-replica-5-svc-* - LPUSH Latency',
      'valkey-replica-6-svc-* - LPUSH Latency',
    ];
  }
}

module.exports = new ValkeyCommandDetailDashboard();
module.exports.ValkeyCommandDetailDashboard = ValkeyCommandDetailDashboard;
