class ValkeyCommandDetailDashboard {
  constructor() {
    this.url = 'graph/d/valkey-command-details/valkey-redis-command-detail';
    this.metrics = [
      'All - Total Commands / sec',
      'valkey-primary-1-svc-* - Read and Write rate',
      'valkey-primary-2-svc-* - Read and Write rate',
      'valkey-primary-3-svc-* - Read and Write rate',
      'valkey-replica-4-svc-* - Read and Write rate',
      'valkey-replica-5-svc-* - Read and Write rate',
      'valkey-replica-6-svc-* - Read and Write rate',
      'valkey-primary-1-svc-* - command ops/sec',
      'valkey-primary-2-svc-* - command ops/sec',
      'valkey-primary-3-svc-* - command ops/sec',
      'valkey-replica-4-svc-* - command ops/sec',
      'valkey-replica-5-svc-* - command ops/sec',
      'valkey-replica-6-svc-* - command ops/sec',
      'valkey-primary-1-svc-* - top 10 total time by command',
      'valkey-primary-2-svc-* - top 10 total time by command',
      'valkey-primary-3-svc-* - top 10 total time by command',
      'valkey-replica-4-svc-* - top 10 total time by command',
      'valkey-replica-5-svc-* - top 10 total time by command',
      'valkey-replica-6-svc-* - top 10 total time by command',
      'valkey-primary-1-svc-* - total Time Spent by Command / sec',
      'valkey-primary-2-svc-* - total Time Spent by Command / sec',
      'valkey-primary-3-svc-* - total Time Spent by Command / sec',
      'valkey-replica-4-svc-* - total Time Spent by Command / sec',
      'valkey-replica-5-svc-* - total Time Spent by Command / sec',
      'valkey-replica-6-svc-* - total Time Spent by Command / sec',
      'Commands Totals',
      'valkey-primary-1-svc-* - command percentiles',
      'valkey-primary-2-svc-* - command percentiles',
      'valkey-primary-3-svc-* - command percentiles',
      'valkey-replica-4-svc-* - command percentiles',
      'valkey-replica-5-svc-* - command percentiles',
      'valkey-replica-6-svc-* - command percentiles',
      'valkey-primary-1-svc-* - get latency',
      'valkey-primary-2-svc-* - get latency',
      'valkey-primary-3-svc-* - get latency',
      'valkey-replica-4-svc-* - get latency',
      'valkey-replica-5-svc-* - get latency',
      'valkey-replica-6-svc-* - get latency',
      'valkey-primary-1-svc-* - rpop latency',
      'valkey-primary-2-svc-* - rpop latency',
      'valkey-primary-3-svc-* - rpop latency',
      'valkey-replica-4-svc-* - rpop latency',
      'valkey-replica-5-svc-* - rpop latency',
      'valkey-replica-6-svc-* - rpop latency',
      'valkey-primary-1-svc-* - set latency',
      'valkey-primary-2-svc-* - set latency',
      'valkey-primary-3-svc-* - set latency',
      'valkey-replica-4-svc-* - set latency',
      'valkey-replica-5-svc-* - set latency',
      'valkey-replica-6-svc-* - set latency',
      'valkey-primary-1-svc-* - hset latency',
      'valkey-primary-2-svc-* - hset latency',
      'valkey-primary-3-svc-* - hset latency',
      'valkey-replica-4-svc-* - hset latency',
      'valkey-replica-5-svc-* - hset latency',
      'valkey-replica-6-svc-* - hset latency',
      'valkey-primary-1-svc-* - lpop latency',
      'valkey-primary-2-svc-* - lpop latency',
      'valkey-primary-3-svc-* - lpop latency',
      'valkey-replica-4-svc-* - lpop latency',
      'valkey-replica-5-svc-* - lpop latency',
      'valkey-replica-6-svc-* - lpop latency',
      'valkey-primary-1-svc-* - lrange latency',
      'valkey-primary-2-svc-* - lrange latency',
      'valkey-primary-3-svc-* - lrange latency',
      'valkey-replica-4-svc-* - lrange latency',
      'valkey-replica-5-svc-* - lrange latency',
      'valkey-replica-6-svc-* - lrange latency',
      'valkey-primary-1-svc-* - psync latency',
      'valkey-primary-2-svc-* - psync latency',
      'valkey-primary-3-svc-* - psync latency',
      'valkey-replica-4-svc-* - psync latency',
      'valkey-replica-5-svc-* - psync latency',
      'valkey-replica-6-svc-* - psync latency',
      'rpush latency',
      'lpush latency',
    ];
  }
}

module.exports = new ValkeyCommandDetailDashboard();
module.exports.ValkeyCommandDetailDashboard = ValkeyCommandDetailDashboard;
