const filterOperators = {
  equal: '= (EQUAL)',
  regex: '=~ (REGEX)',
};

module.exports = {
  filterOperators,
  rules: [{
    template: 'PostgreSQL connections in use',
    ruleName: 'Custom test pmm_postgresql_too_many_connections Alerting Rule',
    threshold: '81',
    duration: '301s',
    severity: 'Info',
    folder: 'Experimental',
  }, {
    template: 'MongoDB down',
    ruleName: 'mongodb_down Alerting Rule',
    duration: '5s',
    severity: 'Critical',
    folder: 'MongoDB',
  }, {
    template: 'Memory used by MongoDB connections',
    ruleName: 'pmm_mongodb_connections_memory_usage Alerting Rule',
    threshold: '25',
    duration: '300s',
    severity: 'Warning',
    folder: 'MongoDB',
  }, {
    template: 'Memory used by MongoDB',
    ruleName: 'pmm_mongodb_high_memory_usage Alerting Rule',
    threshold: '80',
    duration: '300s',
    severity: 'Warning',
    folder: 'MongoDB',
  }, {
    template: 'MongoDB restarted',
    ruleName: 'pmm_mongodb_restarted Alerting Rule',
    threshold: '300',
    duration: '60s',
    severity: 'Warning',
    folder: 'MongoDB',
  }, {
    template: 'MySQL down',
    ruleName: 'pmm_mysql_restarted Alerting Rule',
    threshold: '300',
    duration: '60s',
    severity: 'Warning',
    folder: 'MySQL',
  }, {
    template: 'MySQL replication running IO',
    ruleName: 'pmm_mysql_replication_io_running Alerting Rule',
    duration: '60s',
    severity: 'Critical',
    folder: 'MySQL',
  }, {
    template: 'MySQL replication running SQL',
    ruleName: 'pmm_mysql_replication_sql_running Alerting Rule',
    duration: '60s',
    severity: 'Critical',
    folder: 'MySQL',
  }, {
    template: 'MySQL restarted',
    ruleName: 'pmm_mysql_restarted Alerting Rule',
    threshold: '300',
    duration: '60s',
    severity: 'Warning',
    folder: 'MySQL',
  }, {
    template: 'MySQL connections in use',
    ruleName: 'pmm_mysql_too_many_connections Alerting Rule',
    threshold: '80',
    duration: '300s',
    severity: 'Warning',
    folder: 'MySQL',
  }, {
    template: 'Node high CPU load',
    ruleName: 'pmm_node_high_cpu_load Alerting Rule',
    threshold: '80',
    duration: '300s',
    severity: 'Warning',
    folder: 'OS',
  }, {
    template: 'Memory available less than a threshold',
    ruleName: 'pmm_node_low_free_memory Alerting Rule',
    threshold: '20',
    duration: '300s',
    severity: 'Warning',
    folder: 'OS',
  }, {
    template: 'Node high swap filling up',
    ruleName: 'pmm_node_swap_filled_up Alerting Rule',
    threshold: '80',
    duration: '300s',
    severity: 'Warning',
    folder: 'OS',
  }, {
    template: 'PostgreSQL down',
    ruleName: 'pmm_postgresql_down Alerting Rule',
    duration: '60s',
    severity: 'Critical',
    folder: 'PostgreSQL',
  }, {
    template: 'PostgreSQL restarted',
    ruleName: 'pmm_postgresql_restarted Alerting Rule',
    threshold: '300',
    duration: '60s',
    severity: 'Warning',
    folder: 'PostgreSQL',
  }, {
    template: 'PostgreSQL connections in use',
    ruleName: 'pmm_postgresql_too_many_connections Alerting Rule',
    threshold: '80',
    duration: '300s',
    severity: 'Warning',
    folder: 'PostgreSQL',
  }, {
    template: 'ProxySQL server status',
    ruleName: 'pmm_proxysql_server_status Alerting Rule',
    status: '4',
    duration: '300s',
    severity: 'Warning',
    folder: 'MySQL',
  }, {
    template: 'PostgreSQL connections in use',
    templateType: 'BUILT_IN',
    ruleName: 'Rule with BUILT_IN template (activated, without channels)',
    threshold: '100',
    thresholdUnit: '%',
    duration: '1',
    severity: 'Warning',
    filters: [{ label: 'service_name', operator: filterOperators.equal, value: 'pmm-server-postgresql' }],
    channels: [],
    activate: true,
  }, {
    template: 'PostgreSQL connections in use',
    templateType: 'BUILT_IN',
    ruleName: 'Rule with BUILT_IN template (not activated, without channels)',
    threshold: '100',
    thresholdUnit: '%',
    duration: '1',
    severity: 'Critical',
    filters: [{ label: 'service_name', operator: filterOperators.equal, value: 'pmm-server-postgresql' }],
    channels: [],
    activate: false,
  }, {
    template: 'PostgreSQL connections in use',
    templateType: 'BUILT_IN',
    ruleName: 'Rule with BUILT_IN template (activated, with channels)',
    threshold: '100',
    thresholdUnit: '%',
    duration: '1',
    severity: 'Error',
    filters: [{ label: 'service_name', operator: filterOperators.equal, value: 'pmm-server-postgresql' }],
    channels: ['EmailChannelForRules'],
    activate: true,
  }, {
    template: 'PostgreSQL connections in use',
    templateType: 'BUILT_IN',
    ruleName: 'Rule with BUILT_IN template (not activated, with channels)',
    threshold: '100',
    thresholdUnit: '%',
    duration: '1',
    severity: 'Notice',
    filters: [{ label: 'service_name', operator: filterOperators.equal, value: 'pmm-server-postgresql' }],
    channels: ['EmailChannelForRules'],
    activate: false,
  }, {
    template: 'E2E TemplateForRules YAML',
    templateType: 'User-defined (UI)',
    ruleName: 'Rule with User-defined (UI) template (activated, without channels)',
    threshold: '100',
    thresholdUnit: '%',
    duration: '1',
    severity: 'Warning',
    filters: [{ label: 'service_name', operator: filterOperators.equal, value: 'pmm-server-postgresql' }],
    channels: [],
    activate: true,
  }, {
    template: 'E2E TemplateForRules YAML',
    templateType: 'User-defined (UI)',
    ruleName: 'Rule with User-defined (UI) template (not activated, without channels)',
    threshold: '100',
    thresholdUnit: '%',
    duration: '1',
    severity: 'Critical',
    filters: [{ label: 'service_name', operator: filterOperators.equal, value: 'pmm-server-postgresql' }],
    channels: [],
    activate: false,
  }, {
    template: 'E2E TemplateForRules YAML',
    templateType: 'User-defined (UI)',
    ruleName: 'Rule with User-defined (UI) template (activated, with channels)',
    threshold: '100',
    thresholdUnit: '%',
    duration: '1',
    severity: 'Error',
    filters: [{ label: 'service_name', operator: filterOperators.equal, value: 'pmm-server-postgresql' }],
    channels: ['EmailChannelForRules'],
    activate: true,
  }, {
    template: 'E2E TemplateForRules YAML',
    templateType: 'User-defined (UI)',
    ruleName: 'Rule with User-defined (UI) template (not activated, with channels)',
    threshold: '100',
    thresholdUnit: '%',
    duration: '1',
    severity: 'Notice',
    filters: [{ label: 'service_name', operator: filterOperators.equal, value: 'pmm-server-postgresql' }],
    channels: ['EmailChannelForRules'],
    activate: false,
  }, {
    template: 'E2E TemplateForRules YAML',
    templateType: 'User-defined (UI)',
    ruleName: 'Rule with User-defined (UI) template with default params',
    threshold: '',
    thresholdUnit: '%',
    duration: '50',
    severity: 'Notice',
    filters: [{ label: 'service_name', operator: filterOperators.equal, value: 'pmm-server-postgresql' }],
    channels: ['EmailChannelForRules'],
    activate: true,
  }, {
    template: 'range-empty',
    templateType: 'User-defined (UI)',
    ruleName: 'Rule with User-defined (UI) template with default params (empty-range template)',
    threshold: '',
    thresholdUnit: '%',
    duration: '50',
    severity: 'Notice',
    filters: [{ label: 'service_name', operator: filterOperators.equal, value: 'pmm-server-postgresql' }],
    channels: ['EmailChannelForRules'],
    activate: true,
  }, {
    template: 'range-empty',
    templateType: 'User-defined (UI)',
    ruleName: 'Rule with User-defined (UI) template (empty-range template)',
    threshold: '666',
    thresholdUnit: '%',
    duration: '50',
    severity: 'Notice',
    filters: [{ label: 'service_name', operator: filterOperators.equal, value: 'pmm-server-postgresql' }],
    channels: ['EmailChannelForRules'],
    activate: true,
  }, {
    template: 'PostgreSQL connections in use',
    templateType: 'BUILT_IN',
    ruleName: 'Rule with BUILT_IN template (2 filters, PMM-T624)',
    threshold: '100',
    thresholdUnit: '%',
    duration: '1',
    severity: 'Warning',
    filters: [
      { label: 'service_name', operator: filterOperators.equal, value: 'pmm-server-postgresql' },
      { label: 'node_name', operator: filterOperators.equal, value: 'pmm-server' },
    ],
    channels: [],
    activate: true,
  }, {
    template: 'PMM agent down',
    ruleName: 'pmm_agent_down Alerting Rule',
    threshold: null,
    duration: '60s',
    severity: 'Critical',
    folder: 'Experimental',
  }, {
    template: 'PMM agent down',
    ruleName: 'Custom pmm_agent_down Alerting Rule',
    threshold: null,
    duration: '60s',
    severity: 'Critical',
    folder: 'Experimental',
  }],
  templates: [{
    template: 'Memory used by MongoDB connections',
    threshold: '25',
    duration: '300',
    severity: 'Warning',
    expression: '100 / ((node_memory_MemTotal_bytes)\n'
        + '/ on(node_name) group_left(service_name) (mongodb_ss_connections{conn_type="current"} * 1024 * 1024))\n'
        + '> [[ .threshold ]]',
    alert: 'MongoDB high memory usage by connections ({{ $labels.service_name }})',
  }, {
    template: 'Memory used by MongoDB',
    threshold: '80',
    duration: '300',
    severity: 'Warning',
    expression: '100 / ((node_memory_MemTotal_bytes)\n'
        + '/ on(node_name) group_left(service_name) (mongodb_ss_mem_resident * 1024 * 1024))\n'
        + '> [[ .threshold ]]',
    alert: 'MongoDB high memory usage ({{ $labels.service_name }})',
  }, {
    template: 'MongoDB restarted',
    threshold: '300',
    duration: '10',
    severity: 'Warning',
    expression: 'mongodb_instance_uptime_seconds\n'
      + '< [[ .threshold ]]',
    alert: 'MongoDB restarted ({{ $labels.service_name }})',
  }, {
    template: 'MySQL down',
    threshold: null,
    duration: '5',
    severity: 'Critical',
    expression: 'sum by (service_name, node_name) (mysql_up) == 0',
    alert: 'MySQL down ({{ $labels.service_name }})',
  }, {
    template: 'MySQL restarted',
    threshold: '300',
    duration: '10',
    severity: 'Warning',
    expression: 'mysql_global_status_uptime\n'
      + '< [[ .threshold ]]',
    alert: 'MySQL restarted ({{ $labels.service_name }})',
  }, {
    template: 'MySQL connections in use',
    threshold: '80',
    duration: '300',
    severity: 'Warning',
    expression: 'max_over_time(mysql_global_status_threads_connected[5m]) / ignoring (job)\n'
      + 'mysql_global_variables_max_connections\n'
      + '* 100\n'
      + '> [[ .threshold ]]',
    alert: 'MySQL too many connections ({{ $labels.service_name }})',
  }, {
    template: 'Node high CPU load',
    threshold: '80',
    duration: '300',
    severity: 'Warning',
    expression: '(1 - avg by(node_name) (rate(node_cpu_seconds_total{mode="idle"}[5m])))\n'
      + '* 100\n'
      + '> [[ .threshold ]]',
    alert: 'Node high CPU load ({{ $labels.node_name }})',
  }, {
    template: 'Memory available less than a threshold',
    threshold: '20',
    duration: '300',
    severity: 'Warning',
    expression: 'node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes\n'
      + '* 100\n'
      + '< [[ .threshold ]]',
    alert: 'Lack of available memory on the Node ({{ $labels.node_name }})',
  }, {
    template: 'Node high swap filling up',
    threshold: '80',
    duration: '300',
    severity: 'Warning',
    expression: '(1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes))\n'
      + '* 100\n'
      + '> [[ .threshold ]]',
    alert: 'Node swap is filling up ({{ $labels.node_name }})',
  }, {
    template: 'PostgreSQL down',
    threshold: null,
    duration: '5',
    severity: 'Critical',
    expression: 'sum by (service_name, node_name) (pg_up) == 0',
    alert: 'PostgreSQL down ({{ $labels.service_name }})',
  }, {
    template: 'PostgreSQL restarted',
    threshold: '300',
    duration: '10',
    severity: 'Warning',
    expression: 'pg_postmaster_uptime_seconds\n'
      + '< [[ .threshold ]]',
    alert: 'PostgreSQL restarted ({{ $labels.service_name }})',
  }, {
    template: 'PostgreSQL connections in use',
    threshold: '80',
    duration: '300',
    severity: 'Warning',
    expression: 'sum(pg_stat_activity_count{datname!~"template.*|postgres"})\n'
      + '> pg_settings_max_connections * [[ .threshold ]] / 100',
    alert: 'PostgreSQL too many connections ({{ $labels.service_name }})',
  }, {
    template: 'E2E TemplateForRules YAML',
    threshold: '80',
    duration: '300',
    severity: 'Warning',
    expression: 'max_over_time(mysql_global_status_threads_connected[5m]) / ignoring (job)\n'
      + 'mysql_global_variables_max_connections\n'
      + '* 100\n'
      + '> [[ .threshold ]]',
    alert: 'MySQL too many connections (instance {{ $labels.instance }})',
  }],
};
