name: _FB integration CLI tests

on:
  workflow_dispatch:
    inputs:
      pmm_ui_tests_branch:
        description: 'pmm-ui-tests repository branch(CLI tests)'
        default: 'main'
        required: false
        type: string
      pmm_qa_branch:
        description: 'pmm-qa repository branch(for setup)'
        default: 'main'
        required: false
        type: string
      pmm_server_image:
        description: 'PMM Server docker image'
        default: 'perconalab/pmm-server:dev-latest'
        required: false
        type: string
      pmm_client_image:
        description: 'pmm2-client docker image'
        default: 'perconalab/pmm-client:dev-latest'
        required: false
        type: string
      pmm_client_version:
        description: "PMM Client Tarball link or Dev-latest"
        default: 'dev-latest'
        required: false
        type: string
      sha:
        description: "SHA (leave empty if running manually, default - 'null')"
        required: false
        type: string

jobs:
  help-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
      cli_test: 'pmm-ui-tests/cli/tests/help.spec.ts'
      test_name: 'help tests'

  pmm-server-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
      cli_test: 'pmm-server-only'
      test_name: 'pmm-server container tests'

  pmm-client-container-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
      cli_test: 'pmm-client-docker'
      services_list: '--setup-pmm-client-docker'
      test_name: 'pmm-client docker'

  ps-57-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
      cli_test: 'pmm-ui-tests/cli/tests/perconaMySqlServer.spec.ts'
      services_list: '--ps-version=5.7 --addclient=ps,1'
      test_name: 'Percona Server 5.7'

  ps-80-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
      cli_test: 'pmm-ui-tests/cli/tests/perconaMySqlServer.spec.ts'
      services_list: '--ps-version=8.0 --addclient=ps,1'
      test_name: 'Percona Server 8.0'

  mysql-80-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
      cli_test: 'pmm-ui-tests/cli/tests/mysql.spec.ts pmm-ui-tests/cli/tests/mysql-conf-file.spec.ts'
      services_list: '--ms-version=8.0 --addclient=ms,1'
      test_name: 'MySQL 8.0'

#      pdpgsql13,

#      pdpgsql14,

#      pdpgsql15,

#      modb4.4,

#      modb5,

#      modb6,

#      generic,

#      haproxy,

#      proxysql,

#      remove ]

