name: _FB integration CLI tests

on:
  workflow_dispatch:
    inputs:
      pmm_server_image:
        description: "pmm-server docker image, default perconalab/pmm-server:dev-latest"
        required: false
        type: string
      pmm_client_version:
        description: "pmm2-client version Tarball or Dev-latest, default is dev-latest"
        required: false
        type: string
      pmm_client_image:
        description: "pmm2-client docker image, default perconalab/pmm-client:dev-latest"
        required: false
        type: string
      pmm_qa_branch:
        description: "Branch for PMM-QA to checkout"
        required: false
        type: string
      pmm_ui_tests_branch:
        description: "Branch for PMM-UI(CLI) tests to checkout"
        required: false
        type: string
      sha:
        description: "SHA (leave empty if running manually, default - 'null')"
        required: false
        type: string

jobs:
  get_versions:
    name: Get versions
    uses: ./.github/workflows/pmm-version-getter.yml
    with:
      repository: ${{ inputs.pmm_server_case || 'release candidate'}}

  pmm-server-tests:
    name: 'PMM Server ${{needs.get_versions.outputs.finish_version}} containers tests'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    needs: get_versions
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
      cli_test: 'pmm-server-only'

  # [ps5.7, ps8, ms8.0, pdpgsql13, pdpgsql14, pdpgsql15, modb4.4, modb5, modb6, help, generic, clientContainer, haproxy, proxysql, remove]

  pmm-client-container-tests:
    name: 'PMM Client Docker Container tests'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    needs: get_versions
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
      cli_test: 'pmm-client-docker'
      services_list: '--setup-pmm-client-docker'
