name: _FB tarball tests

on:
  workflow_dispatch:
    inputs:
      package_testing_branch:
        description: 'Target branch for package-testing repository'
        type: string
        default: 'master'
        required: true
      pmm_server_image:
        description: "pmm-server docker image"
        required: true
        type: string
        default: "perconalab/pmm-server:dev-latest"
      pmm_client_tarball:
        description: "PMM Client tarball link or FB-code"
        default: 'dev-latest'
        type: string
        required: true
      metrics_mode:
        description: 'Select the Metrics Mode for PMM Client:'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - push
          - pull
      sha:
        description: "SHA (leave empty if running manually, default - 'null')"
        required: false
        type: string

  workflow_call:
    inputs:
      package_testing_branch:
        description: 'Target branch for package-testing repository'
        type: string
        default: 'master'
        required: false
      pmm_server_image:
        description: "pmm-server docker image"
        required: true
        type: string
        default: "perconalab/pmm-server:dev-latest"
      pmm_client_tarball:
        description: "PMM Client tarball link or FB-code"
        type: string
        required: true
      metrics_mode:
        description: 'Select the Metrics Mode for PMM Client:'
        default: 'auto'
        type: string
      sha:
        description: "SHA (leave empty if running manually, default - 'null')"
        required: false
        type: string

    secrets:
      BACKUP_LOCATION_ACCESS_KEY:
        required: false
      BACKUP_LOCATION_SECRET_KEY:
        required: false

jobs:
  tarball_install:
    name: Tarball Install test
    uses: ./.github/workflows/package-test-fb.yml@main
    secrets: inherit
    with:
      package_testing_branch: 'master'
      pmm_server_image: ${{ inputs.pmm_server_image }}
      pmm_client_tarball: ${{ inputs.client_version || 'dev-latest' }}
      playbook: 'pmm2-client_integration_custom_port'
      test_name: 'Tarball install'
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}

  tarball_upgrade:
    name: Tarball Upgrade test
    uses: ./.github/workflows/package-test-fb.yml@main
    secrets: inherit
    with:
      package_testing_branch: 'master'
      pmm_server_image: ${{ inputs.server_image || 'perconalab/pmm-server:dev-latest' }}
      pmm_client_tarball: ${{ inputs.client_version || 'dev-latest' }}
      playbook: 'pmm2-client_integration_upgrade_custom_path'
      test_name: 'Tarball upgrade'
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}