name: PMM Integration Tests

on:
  workflow_dispatch:
    inputs:
      pmm_ui_tests_branch:
        description: 'pmm-ui-tests repository branch(CLI tests)'
        default: 'v3'
        required: false
        type: string
      qa_integration_branch:
        description: 'qa_integration repository branch(for setup)'
        default: 'v3'
        required: false
        type: string
      pmm_server_image:
        description: 'PMM Server docker image'
        default: 'perconalab/pmm-server:3-dev-latest'
        required: false
        type: string
      pmm_client_image:
        description: 'pmm3-client docker image'
        default: 'perconalab/pmm-client:3-dev-latest'
        required: false
        type: string
      pmm_client_version:
        description: 'PMM Client version (3-dev-latest|pmm3-rc|x.xx.x|https...)'
        default: '3-dev-latest'
        required: false
        type: string
      sha:
        description: "SHA (leave default if running manually)"
        default: 'null'
        required: false
        type: string

  workflow_call:
    inputs:
      pmm_ui_tests_branch:
        required: false
        type: string
      qa_integration_branch:
        required: false
        type: string
      pmm_server_image:
        required: true
        type: string
      pmm_client_image:
        required: true
        type: string
      pmm_client_version:
        required: true
        type: string
      sha:
        required: false
        type: string

jobs:
  help-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'pmm-ui-tests/cli/tests/help.spec.ts'
      test_name: 'help tests'

  pmm-server-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'pmm-server-only'
      test_name: 'pmm-server container'

  pmm-client-container-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'pmm-client-docker'
      services_list: '--database dockerclients'
      test_name: 'pmm-client docker'

  generic-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'generic unregister --workers=1'
      test_name: 'Generic'

  remove-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'pmm-ui-tests/cli/tests/remove.spec.ts'
      test_name: 'Remove'

  ps-57-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'pmm-ui-tests/cli/tests/perconaMySqlServer.spec.ts'
      services_list: '--database ps=5.7'
      test_name: 'Percona Server 5.7'

  ps-80-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'pmm-ui-tests/cli/tests/perconaMySqlServer.spec.ts'
      services_list: '--database ps=8.0'
      test_name: 'Percona Server 8.0'

  mysql-80-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'pmm-ui-tests/cli/tests/mysql.spec.ts pmm-ui-tests/cli/tests/mysql-conf-file.spec.ts --workers=1'
      services_list: '--database mysql=8.0'
      test_name: 'MySQL 8.0'

  pdpgsql-14-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'postgreSql --workers=1'
      services_list: '--database pdpgsql=14'
      test_name: 'PD PostgreSQL 14'

  pdpgsql-15-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'postgreSql --workers=1'
      services_list: '--database pdpgsql=15'
      test_name: 'PD PostgreSQL 15'

  pdpgsql-16-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'postgreSql --workers=1'
      services_list: '--database pdpgsql=16'
      test_name: 'PD PostgreSQL 16'

  # FIXME: PMM-12966
  #  mongo-44-tests:
  #    name: 'CLI / Integration'
  #    uses: ./.github/workflows/runner-integration-cli-tests.yml
  #    secrets: inherit
  #    with:
  #      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
  #      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
  #      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
  #      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:dev-latest' }}
  #      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:dev-latest' }}
  #      pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
  #      cli_test: 'pmm-ui-tests/cli/tests/mongoDb.spec.ts'
  #      services_list: '--modb-version=4.4 --addclient=modb,1'
  #      test_name: 'MongoDB 4.4'

  # FIXME: PMM-12966
  #  mongo-5-tests:
  #    name: 'CLI / Integration'
  #    uses: ./.github/workflows/runner-integration-cli-tests.yml
  #    secrets: inherit
  #    with:
  #      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
  #      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
  #      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
  #      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:dev-latest' }}
  #      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:dev-latest' }}
  #      pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
  #      cli_test: 'pmm-ui-tests/cli/tests/mongoDb.spec.ts'
  #      services_list: '--modb-version=5 --addclient=modb,1'
  #      test_name: 'MongoDB 5.x'

  # FIXME: PMM-12966
  #  mongo-6-tests:
  #    name: 'CLI / Integration'
  #    uses: ./.github/workflows/runner-integration-cli-tests.yml
  #    secrets: inherit
  #    with:
  #      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
  #      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
  #      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
  #      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:dev-latest' }}
  #      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:dev-latest' }}
  #      pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
  #      cli_test: 'pmm-ui-tests/cli/tests/mongoDb.spec.ts'
  #      services_list: '--modb-version=6 --addclient=modb,1'
  #      test_name: 'MongoDB 6.x'
  # FIXME: PMM-12966
  #  mongo-7-tests:
  #    name: 'CLI / Integration'
  #    uses: ./.github/workflows/runner-integration-cli-tests.yml
  #    secrets: inherit
  #    with:
  #      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
  #      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'main' }}
  #      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
  #      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:dev-latest' }}
  #      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:dev-latest' }}
  #      pmm_client_version: ${{ inputs.pmm_client_version || 'dev-latest' }}
  #      cli_test: 'pmm-ui-tests/cli/tests/mongoDb.spec.ts'
  #      services_list: '--modb-version=7 --addclient=modb,1'
  #      test_name: 'MongoDB 7.x'

  psmdb-5-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'pmm-ui-tests/cli/tests/mongoDb-psmdb.spec.ts'
      services_list: '--database psmdb=5,SETUP_TYPE=pss'
      test_name: 'PSMDB 5.x'

  psmdb-6-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'pmm-ui-tests/cli/tests/mongoDb-psmdb.spec.ts'
      services_list: '--database psmdb=6,SETUP_TYPE=shards'
      test_name: 'PSMDB 6.x'

  psmdb-7-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'pmm-ui-tests/cli/tests/mongoDb-psmdb.spec.ts'
      services_list: '--database psmdb=7,SETUP_TYPE=shards'
      test_name: 'PSMDB 7.x'

  haproxy-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'haproxy'
      services_list: '--database=haproxy'
      test_name: 'HA Proxy'

  pxc-57-proxysql-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'proxySql'
      services_list: '--database pxc=5.7'
      test_name: 'PXC 5.7'

  pxc-80-proxysql-tests:
    name: 'CLI / Integration'
    uses: ./.github/workflows/runner-integration-cli-tests.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      qa_integration_branch: ${{ inputs.qa_integration_branch || 'v3' }}
      pmm_server_image: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      pmm_client_image: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      pmm_client_version: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      cli_test: 'proxySql'
      services_list: '--database pxc=8.0'
      test_name: 'PXC 8.0'
