name: Runner Easy Install
on:
  workflow_dispatch:
    inputs:
      runs_on:
        description: 'Select Architecture tu run test on'
        default: 'ubuntu-24.04'
        required: true
        type: choice
        options:
          - ubuntu-24.04
          - ubuntu-24.04-arm
      pmm_ui_tests_branch:
        description: "Branch for PMM-UI tests to checkout"
        required: false
        type: string
      qa_integration_branch:
        description: "Branch for qa-integration to checkout"
        required: false
        type: string
      pmm_server_image:
        description: 'PMM Server docker image'
        default: 'perconalab/pmm-server:3-dev-latest'
        required: false
        type: string
      os:
        description: "Select OS to run test in:"
        required: true
        default: "jammy"
        type: choice
        options:
          - ubuntu-noble
          - ol-9

  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
      pmm_ui_tests_branch:
        required: false
        type: string
      qa_integration_branch:
        required: false
        type: string
      pmm_server_image:
        required: false
        type: string
      os:
        required: false
        type: string
jobs:
  pmm_easy_install:
    name: "e2e tests: ${{ inputs.tags_for_tests || '@settings-fb' }}"
    runs-on: ${{ inputs.runs_on }}
    timeout-minutes: 60
    env:
      SHA: ${{ 'null' }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      QA_INTEGRATION_BRANCH: ${{ inputs.qa-integration_branch || 'v3' }}
      PMM_UI_TESTS_BRANCH: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      DOCKER_VERSION: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      PMM_CLIENT_VERSION: ${{ inputs.pmm_client_version || '3-dev-latest' }}

    steps:
      - name: Checkout PMM UI tests
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PMM_UI_BRANCH }}
          repository: percona/pmm-ui-tests
          path: ./pmm-ui-tests

      - name: Checkout qa-integration repo
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PMM_QA_BRANCH }}
          repository: Percona-Lab/qa-integration
          path: ./qa-integration

      - name: Cleanup disk space on a worker according to https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: 'Convert choices'
        run: |
          ### vagrant vm ###
          if [[ "${{ inputs.os }}" =~ "ubuntu-noble" ]]; then
            echo "VM_BOX=bento/ubuntu-24.04" >> $GITHUB_ENV
          fi
          if [[ "${{ inputs.os }}" =~ "ol-9" ]]; then
            echo "VM_BOX=generic/oracle9" >> $GITHUB_ENV
          fi
          echo "${{ env.VM_BOX }}"
          
      - name: "Setup tools"
        run: |
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install -y vagrant

      - name: "Create vagrantfile"
        working-directory: ./
        run: |
          pwd
          # mkdir -p ~/test-vm/
          # cat > ~/test-vm/Vagrantfile <<EOF
          cat > Vagrantfile <<EOF
          Vagrant.require_version ">= 1.7.0"
          Vagrant.configure(2) do |config|
            config.vm.box = "${{ env.VM_BOX }}"
            ${{ contains(env.VM_BOX, 'debian10') && 'config.vbguest.auto_update = true' }}
            config.ssh.insert_key = false
            config.vm.define :CLIENT_TEST do |t|
            end

            config.vm.synced_folder "${{ github.workspace }}/", "/pmm/easy-install/"
            config.vm.provision "shell", privileged: true, inline: <<-SHELL
              ## Set environment variables...
              export PMM_SERVER_IP=10.0.2.2:443
              export METRICS_MODE=${{ env.METRICS_MODE }}
              export PMM_VERSION="${{ env.EXPECTED_VERSION }}"
              echo $PMM_VERSION
            
              cd /pmm/easy-install/
              curl -fsSL https://raw.githubusercontent.com/percona/pmm/refs/heads/v3/get-pmm.sh | /bin/bash
              SHELL
          end

          EOF  

      - name: "Run Vagrant File on ${{ inputs.os }}"
        working-directory: ./
        run: vagrant up