name: runner-e2e-tests-podman
on:
  workflow_dispatch:
    inputs:
      pmm_ui_tests_branch:
        description: "Branch for PMM-UI tests to checkout"
        required: false
        type: string
      qa_integration_branch:
        description: "Branch for qa-integration to checkout"
        required: false
        type: string
      pmm_qa_branch:
        description: "Branch for PMM-QA to checkout"
        required: false
        type: string
      pmm_server_image:
        description: 'PMM Server docker image'
        default: 'perconalab/pmm-server:3-dev-latest'
        required: false
        type: string
      pmm_client_image:
        description: 'pmm2-client docker image'
        default: 'perconalab/pmm-client:3-dev-latest'
        required: false
        type: string
      pmm_client_version:
        description: 'PMM Client version (dev-latest|pmm3-rc|x.xx.x|https...)'
        default: '3-dev-latest'
        required: false
        type: string
      setup_services:
        description: "Setup arguments, ex.: --addclient=ps,1 --ps-version=5.7"
        required: false
        type: string
      tags_for_tests:
        description: "example: @settings-fb"
        required: true
        type: string
      sha:
        description: "SHA (leave default if running manually)"
        default: 'null'
        required: false
        type: string

  workflow_call:
    inputs:
      pmm_ui_tests_branch:
        required: false
        type: string
      pmm_qa_branch:
        required: false
        type: string
      qa_integration_branch:
        required: false
        type: string
      pmm_server_image:
        required: false
        type: string
      pmm_client_version:
        required: false
        type: string
      pmm_client_image:
        required: false
        type: string
      setup_services:
        required: false
        type: string
      tags_for_tests:
        required: true
        type: string
      sha:
        required: false
        type: string

jobs:
  ui-tests-e2e:
    name: "podman e2e tests: ${{ inputs.tags_for_tests || '@settings-fb' }}"
    #    runs-on: ubuntu-latest Mongo Replica setup fails in ubuntu-latest for some reason. Additional investigation needed
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    env:
      SHA: ${{ inputs.sha || 'null' }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PMM_UI_TESTS_BRANCH: ${{ inputs.pmm_ui_tests_branch || 'v3' }}
      PMM_QA_BRANCH: ${{ inputs.pmm_qa_branch || 'v3' }}
      QA_INTEGRATION_BRANCH: ${{ inputs.qa_integration_branch || 'v3' }}
      DOCKER_VERSION: ${{ inputs.pmm_server_image || 'perconalab/pmm-server:3-dev-latest' }}
      CLIENT_DOCKER_VERSION: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      CLIENT_IMAGE: ${{ inputs.pmm_client_image || 'perconalab/pmm-client:3-dev-latest' }}
      CLIENT_VERSION: ${{ inputs.pmm_client_version || '3-dev-latest' }}
      WIZARD_ARGS: ${{ inputs.setup_services || '' }}
      TAGS_FOR_TESTS: ${{ inputs.tags_for_tests || '@settings-fb' }}
      ADMIN_PASSWORD: 'admin-password'

    steps:
      - name: Create status check
        if: ${{ github.event_name != 'pull_request' }}
        uses: percona/gh-action-github-status-action@v1
        continue-on-error: true
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: "${{ env.TAGS_FOR_TESTS }} UI tests"
          description: "Test execution ${{ job.status }}"
          state: "pending"
          repository: ${{ github.repository }}
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          sha: ${{ env.SHA }}

      - name: "Checkout PMM UI tests: ${{ env.PMM_UI_TESTS_BRANCH }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PMM_UI_TESTS_BRANCH }}
          repository: percona/pmm-ui-tests
          path: ./pmm-ui-tests

      - name: "Checkout PMM QA: ${{ env.PMM_QA_BRANCH }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PMM_QA_BRANCH }}
          repository: percona/pmm-qa
          path: ./pmm-qa

      - name: "Checkout qa-integration: ${{ env.QA_INTEGRATION_BRANCH }}"
        uses: actions/checkout@v4
        with:
          ref: ${{ env.QA_INTEGRATION_BRANCH }}
          repository: Percona-Lab/qa-integration
          path: ./qa-integration

      - name: Setup tools
        run: |
          sudo apt-get install -y apt-transport-https ca-certificates dirmngr ansible libaio1 libaio-dev libnuma-dev libncurses5 socat sysbench
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754
          echo "deb https://packages.clickhouse.com/deb stable main" | sudo tee \
              /etc/apt/sources.list.d/clickhouse.list
          . /etc/os-release
          echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee \
              /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
          curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key" | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo apt-get install -y 
          sudo apt-get install -y clickhouse-client podman
          sudo curl -s https://raw.githubusercontent.com/datacharmer/dbdeployer/master/scripts/dbdeployer-install.sh | bash
          ls -la
          pushd ./pmm-qa
          wget https://raw.githubusercontent.com/Percona-QA/percona-qa/master/get_download_link.sh
          chmod +x get_download_link.sh
          popd
          sudo sysctl net.ipv4.ip_unprivileged_port_start=80

      - name: Setup PMM2-Server
        working-directory: ./pmm-ui-tests
        run: |
          mkdir -p ~/.config/systemd/user/
          cat > ~/.config/systemd/user/pmm-server.service <<EOF
          [Unit]
          Description=pmm-server
          Wants=network-online.target
          After=network-online.target
          After=nss-user-lookup.target nss-lookup.target
          After=time-sync.target
          
          [Service]
          Type=simple
          
          # set environment for this unit
          Environment=PMM_HTTP_PORT=80
          Environment=PMM_PUBLIC_PORT=443
          Environment=PMM_VOLUME_NAME=%N
          Environment=PMM_SERVER_IMAGE=docker.io/${{ env.DOCKER_VERSION }}
          Environment=PMM_ENV_FILE=%h/.config/pmm-server/pmm-server.env
          
          # optional env file that could override previous env settings for this unit
          EnvironmentFile=-%h/.config/pmm-server/env
          
          ExecStart=/usr/bin/podman run --rm --replace=true --name=%N -p \${PMM_PUBLIC_PORT}:8443/tcp -p \${PMM_HTTP_PORT}:8080/tcp --ulimit=host --volume=\${PMM_VOLUME_NAME}:/srv --env-file=\${PMM_ENV_FILE} --health-cmd=none --health-interval=disable \${PMM_SERVER_IMAGE}
          ExecStop=/usr/bin/podman stop -t 10 %N
          Restart=on-failure
          RestartSec=20
          
          [Install]
          Alias=%N
          WantedBy=default.target
          
          EOF
          
          mkdir -p ~/.config/pmm-server/
          cat > ~/.config/pmm-server/pmm-server.env <<EOF
          DISABLE_UPDATES=1
          #ENABLE_DBAAS=1
          PMM_DEBUG=1
          PERCONA_TEST_SAAS_HOST=check-dev.percona.com:443
          PMM_DEV_PERCONA_PLATFORM_PUBLIC_KEY=RWTg+ZmCCjt7O8eWeAmTLAqW+1ozUbpRSKSwNTmO+exlS5KEIPYWuYdX
          PMM_DEV_PERCONA_PLATFORM_ADDRESS=https://check-dev.percona.com:443
          PERCONA_TEST_TELEMETRY_INTERVAL=10s
          PERCONA_TEST_TELEMETRY_RETRY_BACKOFF=10s
          
          EOF
          
          systemctl --user enable --now pmm-server
          
          export CONTAINER_NAME="pmm-server"
          export LOGS="pmm-managed entered RUNNING state"
          attempt=0
          while [ $attempt -le 3 ]; do
            attempt=$(( $attempt + 1 ))
            echo "Waiting for ${CONTAINER_NAME} to be up (attempt: $attempt)..."
            result=$(systemctl --user status ${CONTAINER_NAME})
            if grep "${LOGS}" <<< $result ; then
              echo "${CONTAINER_NAME} is ready!"
              break
            fi
            sleep 10
          done;
          timeout 100 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://admin:admin@127.0.0.1/ping)" != "200" ]]; do sleep 5; done' || false
          podman exec pmm-server change-admin-password ${{ env.ADMIN_PASSWORD }}
          # bash -x testdata/db_setup.sh

      - name: Export path to pmm-qa repo
        working-directory: ./pmm-qa
        run: echo "PATH_TO_PMM_QA=$(pwd)" >> $GITHUB_ENV

      - name: Setup PMM3-Client
        working-directory: ./qa-integration/pmm_qa
        run: sudo bash -x pmm3-client-setup.sh --pmm_server_ip 127.0.0.1 --client_version ${{ env.CLIENT_VERSION }} --admin_password ${{ env.ADMIN_PASSWORD }} --use_metrics_mode no

      - name: Run Setup for E2E Tests
        working-directory: ./pmm-qa
        run: sudo -E bash -x pmm-tests/pmm-framework.sh ${{ env.WIZARD_ARGS }} --pmm2

      - name: Setup npm modules for e2e tests
        working-directory: ./pmm-ui-tests
        run: |
          npm ci
          envsubst < env.list > env.generated.list

      - name: Execute e2e tests with tags ${{ env.TAGS_FOR_TESTS }}
        working-directory: ./pmm-ui-tests
        env:
          SERVER_IP : "127.0.0.1"
          PMM_UI_URL : "http://127.0.0.1/"
          PMM_URL : "http://admin:${{ env.ADMIN_PASSWORD }}@${{ env.SERVER_IP }}"
        run: |
          sed -i 's+http://localhost/+${PMM_UI_URL}/+g' pr.codecept.js
          ./node_modules/.bin/codeceptjs run -c pr.codecept.js --grep "${{ env.TAGS_FOR_TESTS }}"

      - uses: actions/github-script@v7
        if: ${{ always() }}
        id: artifact_name
        with:
          script: |
            return `artifacts_for_${process.env.TAGS_FOR_TESTS.replaceAll('|', '')}`
          result-encoding: string

      - name: Create status check
        if: ${{ github.event_name != 'pull_request' && always() }}
        uses: percona/gh-action-github-status-action@v1
        continue-on-error: true
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: "${{ env.TAGS_FOR_TESTS }} UI tests"
          description: "Test execution ${{ job.status }}"
          state: ${{ job.status }}
          repository: ${{ github.repository }}
          target_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          sha: ${{ env.SHA }}

#      - name: Setup tmate session  on failure
#        if: ${{ failure() }}
#        uses: percona-platform/action-tmate@v2
